config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/show'
  root to: 'pages#home'
  devise_for :users
  # resources :users, only: [:new, :create]

  #                           AS CAMPER       / AS OWNER STARTING AT NEW
  resources :campsites, only: [:index, :show, :new, :create] do
    resources :reservations, only: [:new, :create] # AS CAMPER
  end

  # AS BOTH
  resource :dashboard, only: [:show]

  # AS OWNER
  resources :reservations, only: [:show] do
    member do
      patch :confirm
      patch :decline
    end

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campsite.rb
class Campsite < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :address, presence: true
  validates :price, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :campsite
  validates :arrival, presence: true
  validates :departure, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reservations, dependent: :destroy
  validates :first_name, presence: true
  validates :email, uniqueness: true, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/campsites_controller.rb
class CampsitesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_campsite, only: [:show, :edit, :update]
  skip_before_action :authenticate_user!, only: :index

  def new
    @campsite = Campsite.new
    authorize @campsite # authorize if user can make new campsite
  end

  def create
    @user = current_user # find the current user (this is a devise spefic method)
    @campsite = Campsite.new(campsite_params) # create a new campsite
    authorize @campsite # authorize if campsite can be created by user
    @campsite.user = @user # attach the user instance to the new campsite instance
    @campsite.save # save the newly created campsite

    redirect_to dashboard_path

    flash[:notice] = "Your campsite '#{@campsite.name}' has been saved!"
  end

  def show
    @reservation = Reservation.new
    @campsite = Campsite.find(params[:id])
    authorize @campsite
  end

  def index
    if params[:query] && params[:query][:city].present?
      sql_query = " \
        campsites.name @@ :query \
        OR campsites.address @@ :query \
      "
      @campsites = policy_scope(Campsite.where(sql_query, query: "%#{params[:query][:city]}%"))
    else
      @campsites = policy_scope(Campsite) #authorize the campsites
    end
  end

  private

  def set_campsite
    @campsite = Campsite.find(params[:id])
  end

  def campsite_params
    params.require(:campsite).permit(:name, :address, :price, :photo, :user_id, :description)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_after_action :verify_authorized, only: [:show]
  def show
    @reservations = Reservation.find(current_user.reservation_ids)
    @campsite = Campsite.where(user: current_user)
    @newres = Reservation.where(campsite: @campsite.ids)
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_reservation, only: [:show, :edit, :update, :confirm, :decline]
  skip_before_action :authenticate_user!, only: :index

  def new
    @reservation = Reservation.new
    authorize @reservation # authorize if user can make new campsite
  end

  def create
    @user = current_user # find the current user (this is a devise spefic method)
    @campsite = Campsite.find(params[:campsite_id])
    @reservation = Reservation.new(reservation_params) # create a new campsite

    authorize @reservation # authorize if campsite can be created by user
    @reservation.campsite = @campsite
    @reservation.user = @user # attach the user instance to the new campsite instance
    @reservation.total_price = (@reservation.departure - @reservation.arrival).to_i
    @reservation.status = "Pending"
    @reservation.save # save the newly created campsite
    redirect_to dashboard_path
    flash[:notice] = "Your reservation for '#{@campsite.name}' has been saved!"
  end

  def confirm
    authorize @reservation
    @reservation.status = "Confirmed"
    @reservation.save
    redirect_to dashboard_path
    flash[:notice] = "The reservation has been confirmed!"
  end

  def decline
    authorize @reservation
    @reservation.status = "Declined"
    @reservation.save
    redirect_to dashboard_path
    flash[:alert] = "The reservation has been declined!"
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:arrival, :departure)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/campsites/create.html.erb
<h1>Campsites#create</h1>
<p>Find me in app/views/campsites/create.html.erb</p>

app/views/campsites/index.html.erb
<!-- nav bar -->

<%= render "partials/navbar"%>

<!-- search bar  -->
<div class="search-bar-container">
  <div>
    <%= simple_form_for :query, method: :get, url: campsites_path do |f| %>
    <%= f.input :city,
    class: "form-item form-control",
      placeholder: "Place",
      label: false
      %>
    </div>
    <!--  <input type="text" class="form-item form-control" placeholder="Place"> -->
    <div>
      <div class="form-group string required query_city">
        <input type="date" class="form-item form-control" placeholder="check in">
      </div>
    </div>
    <div>
      <div class="form-group string required query_city">
        <input type="date" class="form-item form-control" placeholder="check out">
      </div>
    </div>
    <div>
      <div class="form-group string required query_city">
        <select class="form-item form-control">
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
          <option>6</option>
          <option>7</option>
          <option>8</option>
        </select>
    </div>
  </div>
    <div>
      <div class="form-group string required query_city">
        <%= f.button :submit, "search", :class => "btn btn-warning font-weight-bold form-item button-index-search" %>
        <%#link_to "search", campsites_path, :class=> "btn btn-warning font-weight-bold form-item button-index-search"%>
      </div>
    </div>
    <% end %>
  </div>

  <!-- search results -->

  <div class="main-container">
    <div class="campsite-container">
      <% @campsites.each do |campsite| %>
      <%= link_to(campsite_path(campsite)) do %>
      <div class="campsite-card ">
        <%= cl_image_tag(campsite.photo) %>
        <div class="campsite-card-infos">
          <div>
            <h2><%= campsite.name %></h2>
          </div>
          <h2 class="campsite-card-pricing">€<%= campsite.price.to_i %></h2>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>

app/views/campsites/new.html.erb
<%= render "partials/navbar_signed_in"%>

  </nav>
</div>

<div class= "main-container">
  <div class ="listing-container">

    <div class="listing-form">

      <h2>Create a new listing</h2>
      <%= simple_form_for([@user, @campsite]) do |f| %>
      <div class="form-inputs px-3">

        <%= f.input :name %>
        <%= f.input :description%>
        <%= f.input :address %>
        <%= f.input :price %>

        <%= f.input :photo %>
      </div>

      <div class="form-inputs px-3">
        <%= f.button :submit,  class: "btn btn-warning font-weight-bold p-3 col-sm-12"%>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/campsites/show.html.erb
<%= render "partials/navbar"%>

<!-- details of campsite and search form-->
 <% if @campsite.user == current_user %>
  <%= render "partials/show_campsite_owner" %>
<% else %>
  <%= render "partials/show_campsite_camper" %>

<% end %>




<div class="footer">
  <!-- <p>Follow us</p> -->
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/dashboards/show.html.erb
<!-- nav bar -->
<%= render "partials/navbar_dash"%>


<!-- New reservations -->
<%= render "partials/greetings" %>
<% unless @newres.empty? %>
<%= render "partials/new_reservations"%>
<% end  %>
<!-- Your campsites -->
<% unless @campsite.empty? %>
<%= render "partials/my_campsites", campsites: @campsite%>
<% end  %>

<!-- Your trips -->

<%= render "partials/my_trips"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Campyr</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>


    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<!-- nav bar -->


<%= render "partials/navbar"%>


<!-- banner  -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= image_path 'background.jpg' %>');">

  <div class="search-form">
    <div class="row justify-content-center pt-3">
      <div class="col-sm-10">
        <h2 class="mb-4 text-align-center">Search your next trip</h2>
        <!-- <form> -->
          <div class="form-row">
            <div class="col-sm-10">
              <label>Where do you want to camp?</label>


              <!-- simple-form -->
              <%= simple_form_for :query, method: :get, url: campsites_path do |f| %>
              <%= f.input :city, label: false,
              class: "form-control",
                placeholder: "City"
                %>
              </div>
            </div>
            <div class="form-row">
              <div class="col-sm-10 form-group">
                <label>Check in</label>
                <input type="date" class="form-control" placeholder="date">
              </div>
            </div>
            <div class="form-row">
              <div class="col-sm-10 form-group">
                <label>Check out</label>
                <input type="date" class="form-control" placeholder="date">
              </div>
            </div>
            <!-- drop down -->
            <div class="form-row">
              <div class="col-sm-10 form-group">
                <label for="exampleFormControlSelect1">How many people?</label>
                <select class="form-control" id="exampleFormControlSelect1">
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                  <option>4</option>
                </select>
              </div>
            </div>
            <div class="form-row">
              <%= f.button :submit, 'search campsites', :class => "btn btn-warning font-weight-bold col-sm-10 form-group p-3"  %>
              <% end %>
            </div>
            <!-- </form> -->
          </div>
        </div>
      </div>
    </div>

  <!-- footer  -->
  <%= render "partials/footer" %>

app/views/partials/_footer.html.erb
<div class="footer">
  <!-- <p>Follow us</p> -->
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/partials/_greetings.html.erb
<div class="dashboard-container">
 <h3 class="text-warning"> Hello, <%=current_user.first_name%> !</h3>
</div>

app/views/partials/_list_campsite.html.erb
<div class="modal fade" id="ModalSignin" tabindex="-2" role="dialog" aria-labelledby="testlabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header text-center">
        <h4 class="modal-title" id="myModalLabel">Sign in campsite</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

      </div>
  <%= render "/devise/sessions/newcamp" %>
  </div>
</div>
</div>

app/views/partials/_modal_signup.html.erb
<!-- Modal -->
<div class="modal fade" id="ModalSignup" tabindex="-1" role="dialog" aria-labelledby="testlabel" aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header text-center">
        <h4 class="mb-4 text-align-center">Sign-up to Campyr!</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="container">
      <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
             <%= f.error_notification %>

             <div class="form-inputs">
               <%= f.input :first_name, required: true, autofocus: true %>
               <%= f.input :last_name, required: true, autofocus: true %>
               <%= f.input :email, required: true, autofocus: true %>
               <%= f.input :password, required: true %>
               <%= f.input :password_confirmation, required: true %>


                  </div>

      </div>
      <div class="modal-footer">
        <div class="btn btn-warning form-actions">
              <%= f.button :submit, "Sign up", class: "btn btn-warning" %>
            </div>
        <% end %>
</div>
</div>
</div>
</div>

app/views/partials/_my_campsites.html.erb
<div class="dashboard-container">
  <h4 class="m-3">My campsites</h4>
  <div class="grid-container">

      <!-- each  -->
    <% campsites.each do |campsites| %>
    <%= link_to(campsite_path(campsites)) do %>
      <div class="campsite-card ">
         <img src=<%= cl_image_path campsites.photo%>>
        <div class="campsite-card-infos d-flex justify-content-center">
          <div>
            <h2><%= campsites.name %></h2>
          </div>
        </div>
      </div>
         <% end %>
         <% end %>
      <!-- end of each -->

  </div>
</div>

app/views/partials/_my_trips.html.erb
<div class="dashboard-container">
  <h4>My next trips</h4>
  <div class="grid-container">
    <% @reservations.each do |reservation| %>
    <%= link_to(campsite_path(reservation.campsite)) do %>
    <div class="card-review-reservation"> <h1></h1>
      <img src=<%= cl_image_path Campsite.find(reservation.campsite_id).photo, height: 300, width: 400, crop: :fill %>>
      <div class="card-review-reservation-infos pl-3">
        <h2 class="pb-2"><strong><%=Campsite.find(reservation.campsite_id).name %></strong></h2>
        <div class="row pl-3">
          <p>Arrival: <%= reservation.arrival %></p>&nbsp &nbsp &nbsp &nbsp&nbsp&nbsp <p>Departure: <%= reservation.departure %></p>
        </div>
        <p>Status: <%= reservation.status %> </p>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar">
    <div class="logo-header">
    <%= link_to root_path do %>
    <%= image_tag('logo-camping.png') %>
    <% end %>
    <h1 class="text-align-left">Campyr</h1>
</div>
<div class="d-flex">
  <% if user_signed_in? %>
    <a href="/campsites/new">List your campsite</a>
    <% else %>
    <a data-toggle="modal" data-target="#ModalSignin" href="/campsites/new">List your campsite</a>
      <%= render "partials/list_campsite"%>
    <% end %>

     <% if user_signed_in? %>
   <div class="nav-item active">
     <%= link_to "Dashboard", dashboard_path(@user), class: "navlink"  %>
     <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navlink"  %>
   </div>
        <% else %>
    <div class="nav-item active d-flex">
      <a data-toggle="modal" data-target="#ModalSignin" href="">Sign in</a>
      <%= render "partials/sign_in"%>
    </div>
    <div class="nav-item active">
      <a data-toggle="modal" data-target="#ModalSignup" href="">Sign up</a>
      <%= render "partials/modal_signup"%>
    </div>
  <% end %>

  </div>
  </nav>

app/views/partials/_navbar_dash.html.erb
<nav class="navbar">
  <div class="logo-header">
    <%= link_to root_path do %>
    <%= image_tag('logo-camping.png') %>
    <% end %>

    <h1 class="text-align-left">Campyr</h1>
  </div>
  <div class="d-flex">
    <a href="/campsites/new">List your campsite</a>
    <div class="nav-item active">
     <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navlink"  %>
   </div>


</div>
</nav>

app/views/partials/_navbar_signed_in.erb
<nav class="navbar">
    <div class="logo-header">
    <%= link_to root_path do %>
    <%= image_tag('logo-camping.png') %>
    <% end %>
    <h1 class="text-align-left">Campyr</h1>
</div>
<div class="d-flex">

   <div class="nav-item active">
     <%= link_to "Dashboard", dashboard_path(@user), class: "navlink"  %>
     <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navlink"  %>
   </div>

  </nav>

app/views/partials/_new_reservations.html.erb
<div class="dashboard-container">
<h4>My campsite reservations</h4>
  <div class="grid-container">
    <% @newres.each do |reservation| %>
    <div class="card-review-reservation">
      <a data-toggle="modal" data-target="#reservation-modal-<%= reservation.id %>" class="m-0">
       <img src=<%= cl_image_path reservation.campsite.photo, height: 400, width: 400, crop: :fill %>>
      </a>

      <div class="card-review-reservation-infos p-3">

        <h2><strong><%=reservation.campsite.name %></strong></h2>
        <p><%= reservation.user.first_name %> <%= User.find(reservation.user_id).last_name %></p>

        <div class="row pl-3">
          <p>Arrival: <%= reservation.arrival %></p>&nbsp &nbsp &nbsp &nbsp&nbsp&nbsp
          <p>Departure: <%= reservation.departure %></p>
        </div>

        <p>Status of reservation: <%= reservation.status %></p>
      </div>
    </div>

    <%= render "partials/res_confirmation", reservation: reservation %>
    <% end %>
  </div>
</div>

app/views/partials/_res_confirmation.html.erb
<div class="modal fade" id="reservation-modal-<%= reservation.id %>" tabindex="-1" role="dialog" aria-labelledby="testlabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title" id="myModalLabel"></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="container">
          <div class="card-review-reservation-infos p-3">

            <h2><strong><%=reservation.campsite.name %></strong></h2>
            <p><%= reservation.user.first_name %> <%= reservation.user.last_name %></p>

            <div class="row pl-3">
              <p>Arrival: <%= reservation.arrival %></p>&nbsp &nbsp &nbsp &nbsp&nbsp&nbsp
              <p>Departure: <%= reservation.departure %></p>
            </div>

            <p>Status of reservation: <%= reservation.status %></p>
          </div>
          <div class="form-row">

            <%= link_to "Accept", confirm_reservation_path(reservation), method: :patch, class: "btn btn-primary m-2"%>
            <%= link_to "Decline", decline_reservation_path(reservation), method: :patch, class: "btn btn-warning m-2"%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_search_form.html.erb
<%= simple_form_for :query, method: :get, url: campsites_path do |f| %>
<%= f.input :city,
class: "form-control",
  placeholder: "City"
  %>
  <% end %>

app/views/partials/_show_campsite_camper.html.erb
<!-- infos about the campsite -->
<div class="main-container">

  <div class="container-info">
    <h1><%= @campsite.name %></h1>
    <div>
      <%= cl_image_tag(@campsite.photo, width: 1000, crop: :fill)%>
    </div>
    <div>
      <div>
        <p><strong>Address: </strong><%= @campsite.address %></p>
        <p><strong>About this campsite: </strong><br><%= @campsite.description %></p>
      </div>
    </div>
  </div>

<!-- booking form -->
    <div id="totalprice"class="booking-form border">
    <% if @campsite.user == current_user %>
    <div class="row justify-content-center pt-3">
      <div class="col-sm-10">
        <h2 class="mb-4 text-align-center">This is your campsite</h2>
      </div>
      <% else %>
      <div class="row justify-content-center pt-3">
        <div class="col-sm-10">
          <h2 class="mb-4 text-align-center">Book this campsite</h2>
          <%= simple_form_for([@campsite, @reservation]) do |f| %>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <div class="form-inputs">

            <%= f.input :arrival%>
            <%= f.input :departure%>

          </div>
          <div class="col-sm-10 form-group">
            <p><strong>Price per night: €<strong id="dayprice"><%= @campsite.price.to_i %></strong></strong></p>
            <p id= "price"><strong>Total: €<%=@campsite.price.to_i %></strong></p>
          </div>
        </div>

        <div class="container">
          <div class="row justify-content-center pt-3">
            <div class="col-sm-10">
              <div class="font-weight-bold p-3">
                <a href="/campsites" class="btn btn-secondary mr-3">Back to Results</a>

                <%= f.button :submit , class: "btn btn-warning"%>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/partials/_show_campsite_owner.html.erb
<!-- infos about the campsite -->
<div class="main-container">

  <div class="container-info-owner">
    <h1><%= @campsite.name %></h1>
    <div>
      <%= cl_image_tag(@campsite.photo, width: 1000, crop: :fill)%>
    </div>
    <div>
      <div class="white-box border">
        <p class="pt-2"><strong>Address: </strong><%= @campsite.address %></p>
        <p class="pb-2"><strong>About this campsite: </strong><br><%= @campsite.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

<!-- <div class="alert " role="alert">
  This is a success alert—check it out!
</div> -->